### ISSUE TITLE
Systematic review of binary ground truth quality

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/fmri-segmentation#25]
In anticipation of #24, I would like the team to review all GT segmentations for this project. To ease the review, I suggest we make a single QC report for the entire dataset and post it here so we can discuss. Make sure to add the SHA of the data used to create the report.

Related to: https://github.com/sct-pipeline/fmri-segmentation/issues/22 https://github.com/sct-pipeline/fmri-segmentation/issues/13

**Comment by rohanbanerjee** [comment]
Adding the QC of all the datasets as a single QC report. These QCs contain the binary ground truth.
[data_qc.zip](https://github.com/sct-pipeline/fmri-segmentation/files/13446163/data_qc.zip)

(Didn't add the SHA of the dataset because we have decided to not upload the dataset to git-annex but to openneuro directly. A list of the datasets can be found at: https://docs.google.com/spreadsheets/d/1xZMuR5OLRRIRWyIJicIqr6znDAaaJUqaOhgLX8qWgJI/edit#gid=0)

**Comment by jcohenadad** [comment]
Thank you @rohanbanerjee , I will review ASAP and I think it would be good if @MerveKaptan also had a look, so we can then find a consensus

**Comment by jcohenadad** [comment]
I suggest we all generate a `qc_fail.yml` and upload it here

**Comment by jcohenadad** [comment]
Number of experts per subject:
- one doing the QC (eg: @jcohenadad)
- one doing the manual corr (eg: @rohanbanerjee @MerveKaptan )

**Comment by jcohenadad** [comment]
Started doing the QC from `sub-hamburgP01` --> `sub-leipzigR48`.
Here are the reports: [Archive.zip](https://github.com/sct-pipeline/fmri-segmentation/files/13478567/Archive.zip)

**Comment by jcohenadad** [comment]
Additional comments:

<details><summary>`sub-nwM*`: Under-segmentation and missing first/last slices</summary>

![Screenshot 2023-11-27 at 1 15 01 PM](https://github.com/sct-pipeline/fmri-segmentation/assets/2482071/339b7dcd-756e-41eb-b5ce-43918077e2b1)

</details>


<details><summary>`sub-nwMW*`: Over-segmentation</summary>

![Screenshot 2023-11-27 at 1 15 06 PM](https://github.com/sct-pipeline/fmri-segmentation/assets/2482071/5af045e5-5e8c-40f0-9f4b-d7cc3b78cad2)

</details>

**Comment by jcohenadad** [comment]
`sub-leipzigP*` --> all GT can be used for training
`sub-genevaR*` --> no GT can be used (oversegmentation)

**Comment by rohanbanerjee** [comment]
Closing this issue as all the ground truths have been reviewed. The predictions/manual correction for each active learning training iteration would be discussed in separate issues.

**Comment by rohanbanerjee** [comment]
Keeping track

**Comment by jcohenadad** [comment]
> Keeping track of all the artifacts subjects in the yml file below:

This is not the right location for this. This issue is called "Systematic review of binary ground truth quality". This tracking needs to go in a specific issue, eg: "Tracking images with artifacts". Moreover, the `exclude.yml` file should be part of the latest version of the dataset, not out-of-sync from it.

**Comment by rohanbanerjee** [comment]
Done in issue #46

**Comment by rohanbanerjee** [comment]
Closing this issue as all the purpose of this issue is solved now.
