### ISSUE TITLE
Perform active learning to correct problematic segmentations

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/fmri-segmentation#29]
Related to #25 

Procedure: 
- @jcohenadad finishes #25 
- @rohanbanerjee will re-train a model with the data labeled as ✅ 
- @rohanbanerjee applies the new model to the data with mask labeled as ❌
- @MerveKaptan and @rohanbanerjee will manually correct the masks produced by the latest model ONLY for the mask labeled as ❌
- upload to the dataset
- get new QC by @jcohenadad 
- @rohanbanerjee re-train model

**Comment by rohanbanerjee** [comment]
- We have decided on using the hard labels and nnUNet for our task.

**Comment by rohanbanerjee** [comment]
- We need as streamlined way to select the `good` flagged images from the QC and create a dataset from it. It should select those subjects and create a BIDS dataset accordingly.

Provide more details on this comment.

**Comment by rohanbanerjee** [comment]
The progress of this issue are as follows:

#### What is done
1. Performed by Julien in the issue: https://github.com/sct-pipeline/fmri-segmentation/issues/25
2. Based on the ✅ I made a separate dataset and trained a 3D nnUNet model. This dataset contained 124 subjects in total.
3. After this training was completed, I ran inference on the images that were marked as ❌ and ⚠️. The qc for these images are below.
[20240120_data_excluded_qc.zip](https://github.com/sct-pipeline/fmri-segmentation/files/13993595/20240119_data_excluded_qc.zip)

#### Next steps:
4. Me along with @MerveKaptan will go through the qc and work on manually correcting the images with suboptimal segmentations. 
5. The corrected images will be QCed again
6. The corrected data will be added to the training data corpus and a new nnUNet model will be trained.

**Comment by rohanbanerjee** [comment]
Hello @jcohenadad , after a discussion with @MerveKaptan, we decided that it would be great if you QC'd these predictions. This is would maintain rater consistency and also get your inputs on which subjects we should manually correct. Below is the QC:

[data_excluded_qc_all.zip](https://github.com/sct-pipeline/fmri-segmentation/files/14144806/data_excluded_qc_all.zip)

**Comment by jcohenadad** [comment]
overseg:
![image](https://github.com/sct-pipeline/fmri-segmentation/assets/2482071/598dcb6a-f65e-4801-ab15-d565228560e5)

overseg:
![image](https://github.com/sct-pipeline/fmri-segmentation/assets/2482071/3c5e916a-2267-43e5-8258-4ace1ca844b2)

overseg:
![image](https://github.com/sct-pipeline/fmri-segmentation/assets/2482071/f9a5c4b0-29dc-454c-ae26-ac0e38b052e7)

etc.

how were those predictions generated? can you point to the code, version of model, etc.

**Comment by rohanbanerjee** [comment]
Predictions were generated using the steps mentioned in [comment](https://github.com/sct-pipeline/fmri-segmentation/issues/29#issuecomment-1900981983)

**Comment by rohanbanerjee** [comment]
Closing this issue as we are opening an issue for each round, see #38 , #35 for reference.
