### ISSUE TITLE
Convention for naming sites

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/fmri-segmentation#3]
Each site will have a specific name for the BIDS file prefix:

~~~
- data_northwestern_motor
  - sub-nwM01
- data_northwestern_pain
  - sub-nwP01
- data_leipzig
  - sub-leipzig01
~~~

**Comment by rohanbanerjee** [comment]
Closing this issue as the purpose is solved. All the datasets have been received now which follows the above naming conventions.
