### ISSUE TITLE
information to collect from sites

### ISSUE THREAD

**Issue by MerveKaptan** [sct-pipeline/fmri-segmentation#4]
Hi Julien,

I have added another [example directory](https://github.com/sct-pipeline/fmri-segmentation/tree/main/data_leipzig_rest). 

Could you please look at the following: 

-  [dataset description file](https://github.com/sct-pipeline/fmri-segmentation/blob/main/data_leipzig_rest/dataset_description.json) 
-  [json file associated with the functional data](https://github.com/sct-pipeline/fmri-segmentation/blob/main/data_leipzig_rest/task-rest_bold.json) 

and let me know if you think these contain enough information or whether you would like me to change/add anything? 

Thank you!

**Comment by jcohenadad** [comment]
@MerveKaptan thank you, I am looking at it now. In the future can you please work on a branch and open a [PR](https://github.com/sct-pipeline/fmri-segmentation/pulls), so I can comment and suggest modifications _before merging_. This is how git is supposed to be used. 

Few comments:
- in participants.tsv, the naming is wrong: "sub-ZS001" does not match "sub-leipzigR01". Also see https://github.com/sct-pipeline/fmri-segmentation/issues/3
- The file `sub-leipzigR01_task-rest_desc-moco_bold.nii.gz` is 3D and is the same as `sub-leipzigR01_task-rest_desc-mocomean_bold.nii.gz`, whereas it should be a 4D file containing several EPI volumes. See:
![Screen Shot 2023-01-01 at 5 32 37 PM](https://user-images.githubusercontent.com/2482071/210186436-4544a777-674a-4ac1-9665-5405dbb69962.png)

**Comment by MerveKaptan** [comment]
Hi Julien,

Thanks a lot! 
Oh, I did not know that - I only worked with Git to upload my own analysis code and not with collaborators so apologies for the mistake! I am looking forward to learning and using it properly! 


- I will change the name in the .tsv file! Btw: I have the name "**sub-leipzigR01**" because it is a resting-state dataset. 

- What do you think about the other fields especially the dataset description and the JSON file containing MRI parameters ? @kennethaweberii brought up a good point that some acquisition parameters (such as TE) could slightly change depending on the slice stack etc. so maybe it makes more sense to have such .json file individually for each subject (the output of dcm2niix)?

**Comment by jcohenadad** [comment]
the proper way to do it is use dcm2niix’s JSON output and keep it as sidecar for every NIfTI file.

**Comment by MerveKaptan** [comment]
will change that as well in the new version, thank you!

**Comment by jcohenadad** [comment]
Fixed by https://github.com/sct-pipeline/fmri-segmentation/pull/6
