### ISSUE TITLE
Upload latest GT on OpenNeuro

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/fmri-segmentation#44]
After discussing with @rohanbanerjee I realized that the current GT on OpenNeuro are the original ones provided by the sites. Since then, this GTs have been revisited. We should upload them on OpenNeuro (replace the current ones to avoid confusion).

Related to #30

**Comment by rohanbanerjee** [comment]
The latest GTs have been uploaded to Openneuro and is the [v1.1.0](https://openneuro.org/datasets/ds005143/versions/1.1.0) version of the dataset.

More details:
- List of subjects that have been updated can be found in issues #35, #38 and #40 under the filename `finetuning.yml`
- Script used for updating the data on Openneuro can be found at https://github.com/sct-pipeline/fmri-segmentation/blob/main/scripts/openneuro_data_update.py
- Logic flow of the script
```
1. Reads subjects from the respective yml files (to know which subjects were manually corrected)
2. Copies the manually segmented files from the nnUNet datasets (that were used for training the active learning rounds) to the openneuro dataset.
3. Updates/Appends the json sidecar files with the below information
{	
      'Name': 'Manual',                                        
      'Author': 'Rohan Banerjee and Merve Kaptan (Manually corrected after initial segmentation done by EPISeg model 
      (https://github.com/sct-pipeline/fmri-segmentation/releases/tag/v0.2))',                                         
      'Date': time.strftime('%Y-%m-%d %H:%M:%S')
}

```
The above json file updation follows this [comment](https://github.com/ivadomed/canproco/issues/73#issuecomment-1911067370)

**Comment by rohanbanerjee** [comment]
Steps/Commands followed to download and update the dataset on Openneuro:
```
1. Download the data:
openneuro upload --dataset ds005143 -i openneuro_data

2. Updating the dataset using the script mentioned in the above comment

3. Upload the new snapshot of the dataset: 
openneuro upload --dataset ds005143 -i openneuro_data
```

**Comment by rohanbanerjee** [comment]
> {	
      'Name': 'Manual',                                        
      'Author': 'Rohan Banerjee and Merve Kaptan (Manually corrected after initial segmentation done by EPISeg model 
      (https://github.com/sct-pipeline/fmri-segmentation/releases/tag/v0.2))',                                         
      'Date': time.strftime('%Y-%m-%d %H:%M:%S')
}

There should be three values. For eg in the above json
There should be
- Initial author
- AI Model
- Manual rater

**Comment by rohanbanerjee** [comment]
The mentioned update has been done in the new version of the dataset v1.20 --> https://openneuro.org/datasets/ds005143/versions/1.2.0
