### ISSUE TITLE
Cannot upload data

### ISSUE THREAD

**Issue by MerveKaptan** [sct-pipeline/fmri-segmentation#5]
Hi @jcohenadad ,

I was trying to upload the [example directory](https://github.com/sct-pipeline/fmri-segmentation/tree/main/data_leipzig_rest) and due to its size- I was not able to drag and drop (bigger than 25 MB). 
Then, I tried to upload it via command line (I use Github Desktop) and I get the following error when I push origin:

![ProblemGithub](https://user-images.githubusercontent.com/46893456/210016504-7b2c0ca4-8efb-419e-bc22-79f72f61ed08.png)

I tried logging out and logging in but it did not help. Do I need a special permission to push changes or maybe I did something wrong? Any help is appreciated! 

Thank you very much!

>> PS: I copied and renamed the mean image (as if it was motion-corrected time-series with 20 volumes) to circumvent the issue temporarily

**Comment by jcohenadad** [comment]
> PS: I copied and renamed the mean image (as if it was motion-corrected time-series with 20 volumes) to circumvent the issue temporarily

No, this is not the right way to do this-- it creates confusion (see notably: https://github.com/sct-pipeline/fmri-segmentation/issues/4#issuecomment-1368553947) and it also adds unnecessary physical space on GH's server. 
My suggestion is to just keep the first ~10 volumes of your moco series and upload that.

**Comment by MerveKaptan** [comment]
Okay, thank you very much- will do that after I learn a bit more about correctly using branches!

**Comment by MerveKaptan** [comment]
Hi @jcohenadad,

Apologies for the delay, it was due to the OHBM deadline + being sick.
I am in touch with Rohan and sent him the data today.
I tried to create a PR, I hope it worked now! Once you approve it, I can share the README markdown file that we can have on Github (the information to share with the sites). 

Thank you very much,
Merve

**Comment by jcohenadad** [comment]
Fixed in https://github.com/sct-pipeline/fmri-segmentation/pull/6
