### ISSUE TITLE
deprecated version

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/fmri-segmentation#51]
![image](https://github.com/sct-pipeline/fmri-segmentation/assets/2482071/c1578999-bc8d-4e82-85dc-6eeb58c5631f)

**Comment by jcohenadad** [comment]
once done pls update REAMDE with proper URL

**Comment by rohanbanerjee** [comment]
- The new version v1.2.0 has been uploaded here: https://openneuro.org/datasets/ds005143/versions/1.2.0 
- Updated README with the new URL
