### ISSUE TITLE
Groundtruth for the spinal canal

### ISSUE THREAD

**Issue by abelsalm** [sct-pipeline/fmri-segmentation#58]
Hello,

since I am working on a model to segment the spinal canal : https://github.com/ivadomed/model-canal-seg
Julien suggested me to open an issue here to ask if there was some groundtruth for the spinal canal, to complete and diversify the data I'm using to train and test my model. 
So if anyone has ideas, I'd be glad to hear about it. 

Thanks!

**Comment by jcohenadad** [comment]
@rohanbanerjee @MerveKaptan are you aware of GT spinal canal for the OpenNeuro dataset?

**Comment by rohanbanerjee** [comment]
Hello @abelsalm @jcohenadad , Prof. Rob Barry had shared the GT of the spinal canal. We haven't however uploaded the spinal canal data to Openneuro since our objective was to only upload the spinal cord GT. I will check-in with @MerveKaptan and provide @abelsalm with the data asap!

Thanks!

**Comment by jcohenadad** [comment]
@rohanbanerjee it would be relevant to also upload these GT to OpenNeuro as well-- better to have everything centralized

**Comment by jcohenadad** [comment]
@rohanbanerjee any update?

**Comment by MerveKaptan** [comment]
Hello!! I am so sorry for being MIA! 
I had a very intense course and a work retreat over the weekend. 
I will upload it to openneuro but meanwhile, I am sharing the data with @rohanbanerjee  so he can send it to @abelsalm

**Comment by rohanbanerjee** [comment]
@abelsalm you should have access to the dataset at this link: https://drive.google.com/file/d/1Ryp7_2oMb-X_LdnRkHpHEsvUvEUrsRC2/view?usp=sharing. Let me know if you face any issues accessing it!

**Comment by jcohenadad** [comment]
super!
—
Julien Cohen-Adad, PhD
Canada Research Chair in Quantitative Magnetic Resonance Imaging
Full Professor, Polytechnique Montreal
Director, Functional Neuroimaging Unit, University of Montreal
Associate Member, Mila - Quebec AI Institute
Phone: 514 340 5121 (office: 2264)
Web: https://www.neuro.polymtl.ca/team/faculty/julien-cohen-adad

On Sep 24, 2024, at 11:35 AM, Rohan Banerjee ***@***.***> wrote:



@abelsalm<https://github.com/abelsalm> you should have access to the dataset at this link: https://drive.google.com/file/d/1Ryp7_2oMb-X_LdnRkHpHEsvUvEUrsRC2/view?usp=sharing. Let me know if you face any issues accessing it!
